name: GTFS Validation Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  push:
    branches-ignore:
      - 'refs/pull/**'
  schedule:
    - cron: '0 0 * * *' # Runs every day at 00:00 UTC

jobs:
  test_validate_local_gtfs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run GTFS Validator Action
        id: gtfs-validator
        uses: ./action.yml
        with:
          gtfs-file: examples/alhambra-ca-us.zip
          validator-version: 'latest'
          update-readme-badge: 'true'

      - name: Store Validation Report Artifact
        uses: actions/upload-artifact@v2
        with:
          name: GTFS Validation Report
          path: ${{ steps.gtfs-validator.outputs.validation-report-path }}
